### PR TITLE
unit test for PR #284

### PR DESCRIPTION
**Pull request by go-bears**
added working unit test for git commit feature on command line

### CODE REVIEW

**Comment by go-bears** [comment]
@luckyrome @tjarratt 
@arbonap and I actually wrote a test on our own on our feature!

**Comment by item4** [comment]
Can you merge #284 and #296?

**Comment by go-bears** [comment]
not sure how to merge two different pull requests after I've made them? i think the decision to merge is up to @singingwolfboy and @mitsuhiko ?

**Comment by singingwolfboy** [comment]
@item4: only people in the Lektor organization on GitHub have permission to merge pull requests, so @go-bears can't do so. I'm glad you're excited about this feature, though!

@go-bears @arbonap: Thanks for the work you've done here, but unfortunately, these tests aren't actually testing the code you wrote. They're on a different pull request, so the code you wrote in #284 doesn't exist in this pull request! I think the tests are passing because you mocked out the functions you're trying to test.

In order to add tests for your feature, you want to do so on the same branch that you used for your original pull request. Think about how you would manually test the feature -- what content would you write, what commands would you run, and how would you look at the result to decide if it's working or not? Then automate that in code. I wonder if it's possible to do remote paircoding on this...

**Comment by singingwolfboy** [comment]
I'm actually going to close this pull request, because as I said, the tests for a pull request belong in _that_ pull request, not in a separate one. You don't need this one!

**Pull request closed without merging**
