### PR TITLE
Added quality param for thumbnail generation

### PR DESCRIPTION
**Pull request by tariquesani**
Added quality param for thumbnail generation. 

< img src="{{image.thumbnail(1024,600,crop=true,quality=40)}}" > 

The image filename suffix  will reflect the quality as _q40 being added to the end.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
This needs an automated test or two before it can be merged.

**Comment by tariquesani** [comment]
Not really sure what should be tested here.  Existing tests like test_thumbnail_height just test HTML output.

**Comment by tariquesani** [comment]
Have added a couple of tests for image quality. First tests if the appropriate image file is generated. The second tests if the filesize is below expected size.

**Comment by singingwolfboy** [comment]
This looks great! Thanks so much for the pull request! ✨ 🚀 ✨

**Comment by tariquesani** [comment]
Thanks for merging

**Pull request merged**
