### PR TITLE
Allow more thumbnail options (such as cropping)

### PR DESCRIPTION
**Pull request by jonasvp**
This pull request allows `image.thumbnail()` to receive more options, such as being able to crop an image to a specific size. This first push only contains the crop option, more - such as watermarking, black/white filter, etc. - can easily be added.

It might make sense to generalize the handling more with pluggable image processors and plugin hooks like in [easy-thumbnails](https://github.com/SmileyChris/easy-thumbnails).

 Feedback welcome, let me know which way you want to take this.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
In general I'm all up for improving this but on a quick look at it i do not like the fact that it does not error out on unsupported args. This is just going to make typos very frustrating.

**Comment by jonasvp** [comment]
Hi @mitsuhiko,

good point. I got started on a larger refactor, putting the thumbnailer into a separate class (see previous commit). What do you think? Still needs documentation for the available options, currently it's just `crop=True`.

However, this could be improved a lot by using [Pillow](https://python-pillow.github.io/). Any chance it could be required for thumbnail functionality? Seems to be easily installed under OS X as well, so (I'm guessing) it wouldn't harm the installable app.

**Comment by mitsuhiko** [comment]
@jonasvp i did not manage to bundle pillow on os x in the desktop version. That's part of the reason why I'm not using it.

**Comment by jonasvp** [comment]
@mitsuhiko Ok. Anything you see here that needs improving before it can be merged?

**Comment by mitsuhiko** [comment]
@jonasvp i'm generally for merging it but i might restructure it a little bit. I will try to do it tonight.

**Comment by jonasvp** [comment]
@mitsuhiko Alright! Let me know if I can help.

**Comment by singingwolfboy** [comment]
@mitsuhiko: do you still want this pull request? It currently has some conflicts, so if you want it, the conflicts will need to be resolved before merging. I would recommend [rebasing the pull request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) instead of merging the `master` branch in. @jonasvp, I'm happy to help you with that, if you'd like.

**Comment by mitsuhiko** [comment]
I will close it out for now.

**Pull request closed without merging**
