### PR TITLE
Modified date field type from text to date.

### PR DESCRIPTION
**Pull request by aavrug**

### CODE REVIEW

**Comment by tariquesani** [comment]
What will this change do?

**Comment by aavrug** [comment]
Previously the date fields were displaying just as text field, after this change the date picker popup will display for selection of dates.

**Comment by tariquesani** [comment]
@singingwolfboy  I think we should merge this PR with master. It is a very small change enables the react Datepicker and does not break anything as far as I can tell.

**Comment by singingwolfboy** [comment]
@tariquesani Seems reasonable to me. You want to do so?

**Comment by tariquesani** [comment]
Sure, going ahead.

**Comment by aavrug** [comment]
@tariquesani Thanks for merging.

**Pull request merged**
