### PR TITLE
JS: Some updates and modernisations

### PR DESCRIPTION
**Pull request by yagebu**
### Related Issues / Links

Ref #449

### Description of Changes

Ran `npm update`. Also did a major version bump for jquery (and file-loader).

Changes some default exports to named exports which turned up a little dead code.

### CODE REVIEW

**Comment by yagebu** [comment]
@runfalk: Could you review this PR and my other PR? :)

**Comment by runfalk** [comment]
I will get around to it. I just haven't found the energy yet! :sweat_smile:

It'll try to get it done this week-end, but no promises.

**Comment by runfalk** [comment]
Looks good to me. I've tested it out and it seems to work, hopefully this also fixes broken tests on Node 13.13.

**Comment by yagebu** [comment]
Thanks for reviewing and merging this :)

**Pull request merged**
