### PR TITLE
Fixes #405 Adding py3.6 and node 6 & 7 to Travis-CI

### LINKED ISSUE #405: Make Travis CI Tests more robust
We need to add Python 3.6 to the mix, as well as Node 6 and 7.

Currently Python 2.7 and 3.5 are hit, and the latest stable version of Node is used (8).

### PR DESCRIPTION
**Pull request by nixjdm**

### CODE REVIEW

**Comment by goanpeca** [comment]
@nixjdm I think what you did wont work, we need to add 9 elements in a matrix

**Comment by goanpeca** [comment]
@nixjdm this is ready I think

**Comment by nixjdm** [comment]
Doesn't look like it. I'll refactor it.

**Comment by goanpeca** [comment]
I posted on the wrong PR @nixjdm 

---

I think is clearer if you do something like

```yaml
matrix:
  include:
    - python: 2.7
      env:  TRAVIS_NODE_VERSION=6
    - python: 3.5
      env:  TRAVIS_NODE_VERSION=6
    - python: 3.6
      env:  TRAVIS_NODE_VERSION=6
    - python: 2.7
      env:  TRAVIS_NODE_VERSION=7
    - python: 3.5
      env:  TRAVIS_NODE_VERSION=7
    - python: 3.6
      env:  TRAVIS_NODE_VERSION=7
    - python: 2.7
      env:  TRAVIS_NODE_VERSION=8
    - python: 3.5
      env:  TRAVIS_NODE_VERSION=8
    - python: 3.6
      env:  TRAVIS_NODE_VERSION=8

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION


```

**Comment by nixjdm** [comment]
Thanks @goanpeca! I've been googling around a lot and got most of those pieces together. I'll give that a quick shot. With this are the `python:` and `env:` sections both necessary still?

**Comment by goanpeca** [comment]
Yes you cant have two languages on travis and have it make amtrix for you. You need to specify the mayrix and use one language and an env variable to install thw other.

**Comment by goanpeca** [comment]
@nixjdm now I think I understand your question, you forgot to remove the python versions

```yaml
python:
- "2.7"
- "3.5"
- "3.6"
```

No longer needed.


---

Something like:

```yaml
# https://travis-ci.org/lektor/lektor/
language: python

matrix:
  include:
    # Node 6
    - python: 2.7
      env:  TRAVIS_NODE_VERSION=6
    - python: 3.5
      env:  TRAVIS_NODE_VERSION=6
    - python: 3.6
      env:  TRAVIS_NODE_VERSION=6
    # Node 7
    - python: 2.7
      env:  TRAVIS_NODE_VERSION=7
    - python: 3.5
      env:  TRAVIS_NODE_VERSION=7
    - python: 3.6
      env:  TRAVIS_NODE_VERSION=7
    # Node 8
    - python: 2.7
      env:  TRAVIS_NODE_VERSION=8
    - python: 3.5
      env:  TRAVIS_NODE_VERSION=8
    - python: 3.6
      env:  TRAVIS_NODE_VERSION=8

cache:
  directories:
    - lektor/admin/node_modules

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - python --version
  - node --version

install:
  - travis_retry pip install --upgrade pytest
  - travis_retry pip install --upgrade codecov
  - travis_retry pip install --editable .[test]
  - travis_retry make build-js

script: 
  - make coverage

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f0c538cdfc9883f81e34
```

**Comment by goanpeca** [comment]
Almost there ;-)

screen shot 2017-07-14 at 00 53 54

**Comment by goanpeca** [comment]
@nixjdm not `language: python`, that needs to stay! see my previous comment

**Comment by nixjdm** [comment]
Haha, got it. I wish there were a better way to test this. I'll squash these commits when it's finally done.

**Comment by goanpeca** [comment]
LGTM!

**Pull request merged**
