### PR TITLE
Moving ./example out as a new repo under "lektor" org

### PR DESCRIPTION
**Pull request by kmonsoor**
A new repo can be created under `lektor` org as `lektor-example`.  

Then that repo can be enhanced to include different levels of example site implementations such as `/basic`, `/blog`, `/portfolio`, `/complex` etc.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I keep this under consideration and to be pulled when a new repo appears. Maybe you would be interested in contributing more examples? I can provide you with a repo.

**Comment by kmonsoor** [comment]
yes, that would be great.

**Comment by mitsuhiko** [comment]
Added for you: https://github.com/lektor/lektor-examples

**Comment by singingwolfboy** [comment]
@mitsuhiko @kmonsoor: can this pull request be closed? I'm not clean on what should happen here.

**Comment by mitsuhiko** [comment]
Let's close this out.

**Pull request closed without merging**
