### PR TITLE
Return record children sorted by configured order

### PR DESCRIPTION
**Pull request by ulope**
This updates the `/recordinfo` admin API endpoint to return the list of child pages sorted by the configured order (#174).

It seems to me that there should be a more efficient way than calling `pad.get()` on every child in the sorting lambda but I haven't found it. So if there is a way to optimise this I'd be happy for any pointers.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Hey @ulope, thanks for the pull request! You're right, there's probably a more efficient way of doing this, but I don't know how to do it either. Maybe we can optimize it after the fact -- if it works, that's a good start. :smile:

However, this _does_ need an automated test to make sure that the code you've written does in fact work properly. It would be really annoying to merge unoptimized code only to find out later on that it got broken by another pull request, and nobody noticed!

**Comment by ulope** [comment]
Sorry for the late reply. 
It looks like there are no API tests as of yet. Should we add them to `test_webui.py` or rather add a separate `test_api.py` (for example)?

**Comment by tariquesani** [comment]
@ulope If you are still interested adding  `test_api.py`  would be the way to go...

**Review by tariquesani — CHANGES_REQUESTED** [review]
Needs integration tests

**Pull request merged**
