### PR TITLE
Use pyftpsync for FTP support

### PR DESCRIPTION
**Pull request by daradib**
To improve FTP support, use pyftpsync, which is in turn receiving
support for FTPS (TLS) in mar10/pyftpsync#8.
This also fixes the lack of encryption on the FTP data channel.
For now, pyftpsync is specified as an optional dependency.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Can you clarify what the issue was with the original synching? Because this one does not appear to use listing files which I am not a fan of as FTP is a god-awful protocol and has no support for synching in itself.

**Comment by daradib** [comment]
Sure, here were the problems I encountered:
- Cannot have "@" as part of username in URL, e.g., ftp://myuser@example.com:pass@ftp.example.com. Looks like the problem is with url_parse in werkzeug.urls which does a simple string split. Passing in username with command line argument or environment variable is OK.
- When deploying I frequently get an exception `AttributeError: 'error_reply' object has no attribute 'splitlines'` because FtpConnection.drain_log loops over a log buffer that includes non-string objects.
- I had to manually delete .lektor/listing after each change to redeploy modified files. I didn't investigate why.

Happy to collect more details in the coming days/weeks if you want to try to stick with existing FTP publisher.

**Comment by daradib** [comment]
One issue with pyftpsync is that it prints directly to stdout, so it won't show output in the admin web interface. We could run it under subprocess like rsync/git however. We can also capture stdout in python but would need to add multithreading to simultaneously drain stdout while syncing. We can deal with this later when/if you think pyftpsync is worth considering.

**Comment by mitsuhiko** [comment]
> Cannot have "@" as part of username in URL

You can: `ftp://foo%40bar:baz@blah/` is a perfectly valid URL with a `@` sign in it.  This is also entirely unrelated to pyftpsync.

> When deploying I frequently get an exception AttributeError: 'error_reply' object has no attribute 'splitlines' because FtpConnection.drain_log loops over a log buffer that includes non-string objects.

Sounds like something that should be fixed then.

> I had to manually delete .lektor/listing after each change to redeploy modified files. I didn't investigate why.

Ugh. You are not supposed to delete this file. It's necessary to keep track of the synchronization status. Without that file Lektor would submit each and every file again.

**Comment by daradib** [comment]
> Ugh. You are not supposed to delete this file. It's necessary to keep track of the synchronization status. Without that file Lektor would submit each and every file again.

I know. The problem was that I had made changes to local files (e.g., a template) but Lektor wasn't uploading them. Perhaps a timestamp problem. I will investigate later and file a new issue if needed.

**Pull request closed without merging**
