### PR TITLE
Add Page.prev_item and next_item.

### PR DESCRIPTION
**Pull request by ajdavis**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
That looks good. We should probably name this `next_sibling` and `prev_sibling` though. I think item might be too generic and unclear. Also I wonder if it should be a property of method. I think `get_next_sibling()` might be clearer given that this triggers a query and `.first()` and others are currently methods and not properties.

**Comment by ajdavis** [comment]
Done.

**Comment by mitsuhiko** [comment]
Cool stuff!

**Comment by ajdavis** [comment]
I'll do the docs too.

**Pull request merged**
