### PR TITLE
Update CHANGES with news since 3.2.0

### PR DESCRIPTION
**Pull request by dairiki**
Here are updates to the CHANGES file for changes made since version 3.2.0 was released.

This is a step along to road to making a new (presumably 4.0) release.

I've also renamed `CHANGES` to `CHANGES.md` so that github will format it nicely.

### Issue(s) Resolved

Over 300 commits have been made in the master branch since 3.2.0 was released.  Most have not been mentioned in the changelog.

### Related Issues / Links

See discussion on making a release on #724.

### CODE REVIEW

**Comment by dairiki** [comment]
I've now completed a first pass through the commit log from 3.2.0 through the current master (f135d73).

Comments welcome.

**Comment by andoresuperesu** [comment]
I've done a quick pass and will do a second tomorrow morning (UTC -5). Just to be on the same page, the task would be: see commit by commit reading comments, referenced issues and checking each bugfix is included; right?

**Comment by dairiki** [comment]
> I've done a quick pass and will do a second tomorrow morning (UTC -5). Just to be on the same page, the task would be: see commit by commit reading comments, referenced issues and checking each bugfix is included; right?

Yes, that.

And also, any comments on style, spelling, formatting, wording, or whatever.  I have changed the style a bit from past CHANGES entries.  (E.g. There were no links to issues/PRs before.)

For one thing: Should CHANGES be renamed to CHANGES.md so that github will format it automatically?
Is it included from anywhere else (if so, I havn't found where) such that renaming might break things?

**Comment by andoresuperesu** [comment]
Ok, done, I ran a comparison using `git log 3.2.0..HEAD` as guide and everything seems to be covered. I musk ask, how were you able to produce such changes document updates that fast?

**Comment by dairiki** [comment]
> I musk ask, how were you able to produce such changes document updates that fast?

I just sat down —  with a spare afternoon, a `gitk` window open to browse the commit log, a web browser to look up referenced PRs and tickets, and an editor — and cranked it out.

**Review by andoresuperesu — APPROVED** [review]

**Review by yagebu — APPROVED** [review]

**Pull request merged**
