### PR TITLE
DatePicker Widget

### LINKED ISSUE #49: Give user a cue for date format in blog post create/edit
As an enhancement, giving the user a visual cue of the date format to be entered would be helpful. It took me a while to find default format in api docs. I also tried clicking on the mini-calendar thinking it would pop up a date picker.
screen shot 2015-12-27 at 1 01 14 pm

Overall, a very cool project :sunny:

### PR DESCRIPTION
**Pull request by niijv**
Datepicker Widget done with react-widgets.
Validation is done by the widget itself via parse parameter, so no help text for users if they decide to not use the calendar but input the date manually.

DateTimePicker Widget is also in there but not linked to datetime type yet, as timezone parsing is not fully supported yet on the widget.

Fixes #49
(by providing better means of input)

### CODE REVIEW

**Comment by mdashx** [comment]
Thanks @niijv. A couple weeks ago I used your code to figure out how to add a datepicker myself, just came back to check out if I should get to work on it. Using Lektor everyday now, so I'm definitely looking forward to this branch getting merged.

**Comment by niijv** [comment]
Great to ther @mdashx! Should be in for 2.0, need to get timezone support for the datetime picker working first though.

**Comment by mitsuhiko** [comment]
I will push this into 3.0 just because it's too much for me to review right now.

**Comment by tariquesani** [comment]
Hey @niijv - trying to use this branch gives the following error

lektor admin

Can you give pointers on how to fix?

**Comment by niijv** [comment]
What were your steps after checking out the branch? Did you build it with webpack?

**Comment by tariquesani** [comment]
Oops! but then I did a make build-js and got 

```
ERROR in ./js/widgets/primitiveWidgets.jsx
Module build failed: SyntaxError: /home/tariquesani/Projects//lektor/lektor/admin/static/js/widgets/primitiveWidgets.jsx: Unexpected token (236:34)
    var chunks = inputDateTimeStr.split(' ');
    var dt = this.parseDateTime(inputDateTimeStr);
    if (chunks.length == 3 && !dt.)
    var tz = timezone;
    return false;
  },

```

Thanks

**Comment by niijv** [comment]
@tariquesani That was a complete mess, dunno why. I fixed it, should be working now. But be aware that display of the datetime picker field still has some major issues. Also there is some behaviour which probably shouldnt be how it is currently.

**Comment by tariquesani** [comment]
@niijv Thanks. I will try it out tomorrow and see if I can fix any of the annoyances.

**Comment by zanderle** [comment]
Can't wait for this to be merged! :) 👍

**Comment by singingwolfboy** [comment]
Hey @niijv, thanks for all the work you've done on this! I'm going through some old pull requests to try to clean them out and get this project properly maintained again.

This is a great feature, but the sheer size of the pull request makes it really difficult to review. Could we break it apart into a series of smaller pull requests, and review & merge those one at a time? I'm not super familiar with this code, so it's easier to review in small pieces. (It's OK if the first few pieces have some glaring gaps in functionality!)

**Comment by singingwolfboy** [comment]
Since @niijv doesn't seem interested in pursuing this pull request further, I'm going to close it.

**Comment by tariquesani** [comment]
Why not label it as help wanted ?

**Comment by mitsuhiko** [comment]
If someone wants to pick it up: Go nuts! Help is always wanted :)

**Comment by tariquesani** [comment]
I haven't yet figured out the react local development as yet. Is there a way to develop without having web-pack compile everything everytime

**Comment by mitsuhiko** [comment]
@tariquesani webpack does not support that.

**Comment by niijv** [comment]
@tariquesani If you wanna pick it up and have any questions, I will try to answer them.
Just not enough time to do it myself atm. I hope to get back to it over christmas...

**Comment by tariquesani** [comment]
@niijv my javascript is a bit rusty but I will give it a shot in a day or two... thanks.

**Pull request closed without merging**
