### PR TITLE
fixes #368

### LINKED ISSUE #368: asseturl's relative paths break down on 404 pages
Let's say you have a global `templates/layout.html` which includes your stylesheet as follows:

`<link rel="stylesheet" href="{{ '/static/dist/style.css'|asseturl }}>"`

You also have a `templates/404.html` which extends from `layout.html`.

If you try and access `http://localhost:5000/some-invalid-path/` you'll be greeted with a well styled 404 page.

If you try and access `http://localhost:5000/some-invalid-path/and-another-level-deeper/` you'll get a 404 page which can't load the `/static/dist/style.css` file since `get_asset_url` is going to generate the path `../static/dist/style.css` which will try and get the css from `http://localhost:5000/some-invalid-path/static/dist/style.css` instead of `http://localhost:5000//static/dist/style.css`

screenshot 2017-03-17 14 02 46

One way to fix this is to change https://github.com/lektor/lektor/blob/master/lektor/context.py#L29 to 
```
    return '%s?h=%s' % (
        ctx.source.url_to('!' + asset.url_path, absolute=True),
        info.checksum[:8],
    )
```
Is there a better way to fix this?

### PR DESCRIPTION
**Pull request by anemitz**

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Can you please add a description to this pull request, and an automated test to cover this functionality?

**Comment by anemitz** [comment]
Thinking this through more...should asseturls ever be relative? Seems like most projects would have a dedicated static assets folder and that you'd always want to refer to it using an absolute path. Is that thinking right?

Settings the project's url_style to absolute makes this work as you'd expect so just wondering if making asseturl *always* absolute is the right play.

**Comment by tariquesani** [comment]
> Seems like most projects would have a dedicated static assets folder and that you'd always want to refer to it using an absolute path. Is that thinking right?

Yes.

**Comment by runfalk** [comment]
@anemitz: When using relative URLs you can host Lektor in a sub-folder without issues (like `http://example.com/blog/`. This becomes less trivial if we require absolute paths.

**Comment by yagebu** [comment]
I'm closing this old PR. The corresponding issue has been closed long ago and setting the url style to absolute for the project should be the right fix as mentioned in the issue

**Pull request closed without merging**
