### PR TITLE
Add medium editor

### PR DESCRIPTION
**Pull request by tswicegood**
This PR adds the [react-medium-editor](http://wangzuo.github.io/react-medium-editor/) (React implementation of [this editor](https://yabwe.github.io/medium-editor/)). To see it in action, you need to change a field's `type` to `wsyiwyg`. I'm definitely open to other field name suggestions if you have them.

### CODE REVIEW

**Comment by tswicegood** [comment]
FWIW, I didn't spend any time formatting this once it's dropped in. I think it might be worth a little bit more formatting to make it obvious what's going on with the editor area.

**Comment by mitsuhiko** [comment]
Does this store it as HTML? (I did not look at the implementation yet, just want to understand what it does).

**Comment by tswicegood** [comment]
@mitsuhiko yup -- it's just a presentation layer on top of HTML.

**Comment by mitsuhiko** [comment]
Neat. I need to figure out if we should pull that into Lektor directly or if we can make it somehow work as a plugin. In theory I want something like this in core but i was always hoping it would generate markdown behind the scenes.

**Comment by jungornti** [comment]
Are there any ideas about implementing support different editors/widgets?

**Comment by singingwolfboy** [comment]
Hey @tswicegood, thanks for the pull request! I'm going through some old pull requests to try to clean them out and get this project properly maintained again. Sorry for the long delay in getting to this!

I don't think it makes sense to store HTML directly -- it would be better to have an editor that renders & stores Markdown. I expect that most people using a WYSIWYG will be more comfortable with Markdown than HTML, anyway. There are several other WYSIWYG editor packages out there: I wonder if you can find one that works with Markdown? (I've found [medium-editor-markdown](https://github.com/IonicaBizau/medium-editor-markdown), for example, but it's not implemented in React, unfortunately.) If so, I'd love to see a new pull request with that editor as the default for the `markdown` field type!

If you want to use this, you can always write a [plugin](https://www.getlektor.com/docs/plugins/) for this editor type, but I don't think it makes sense to merge this into the core codebase as-is.

**Pull request closed without merging**
