### PR TITLE
Fix French translation

### PR DESCRIPTION
**Pull request by stephane**
- french quotes
- no double spaces in French
- 'invalide' is for a disability
- 'éditer' is confusing with printing
- simpler sentences
- unbreakable spaces before punctuation
- no plural when none
- primary is 'primaire' not first
- 'invite de commande' means prompt not command
- fix grammar
- term consistency (sous-pages/enfant, enlever/supprimer, error messages)
- translate 'build'

Follow recommendations of http://jacques-andre.fr/faqtypo/lessons.pdf
and http://traduc.org/

### CODE REVIEW

**Comment by stephane** [comment]
Hi @ThomasG77, could you have a look at this, please?

**Comment by stephane** [comment]
Yep, I fixed the missing hyphen in "Voulez vous".

For "commande shell", I used http://glossaire.traduc.org/index.php (with shell command argument). I agree the translation isn't perfect but I think is easy to understand for the target user (developers like us).

Could we keep "construction" in waiting for a better alternative?

**Comment by ThomasG77** [comment]
We can't do better for "construction" and your translation is better than mine in this case. We must accept there are no better solution sometimes. The merge could be done IMO. If there are some issues, we will receive suggestions later (like yours for my initial translation).

**Comment by mitsuhiko** [comment]
JFTR. The current key/value translation system is pretty rubbish. If someone feels like it it would be cool to migrate this to gettext or something better so that this can use transifex and friends in the future.

Should I merge the pull request like this?

**Comment by ThomasG77** [comment]
@mitsuhiko FYI, it seems that JSON for translation is supported with Transifex http://docs.transifex.com/formats/json/

It seems you use json files for translation for [the front-end](https://github.com/lektor/lektor/blob/master/lektor/admin/static/js/i18n.jsx) and [the backend](https://github.com/lektor/lektor/blob/master/lektor/i18n.py). I've already use extensively po files within Sphinx and Transifex.
I'm not sure it's worth to introduce a new dependency on client side for po files management whereas everything could be managed now with JSON files (except maybe plural because Lektor don't seem to use a localization framework on client side)

We have two choices IMO:
- invest time to try and then, make a localization workflow based on JSON with Transifex
- change to gettext because Transifex workflow with it is well known but investigate time to extract and update translation strings and link this workflow with Transifex

I may also miss the point and there is maybe a better and simpler alternative I'm not aware.

@stephane any opinion as it's your PR ;)

**Comment by stephane** [comment]
:+1:  too for the merge.

I think a change of workflow to handle translations is another subject (to talk in a mailing list thread or in a separate issue), as said the current system is pretty rubbish and it won't "scale". In Angular apps, I used angular-gettext with success, http://i18next.com/ seems another good and framework agnostic solution (supports key-based or gettext format). PO format comes with a large set of tools (to handle PO update, merge and so on) and editor modes which they are hard to refuse. 

Once the format/library choice will be settled, the review tool is the next step (PR for translations are painful), Transifex could certainly fit the Lektor needs. Years ago, I was co-maintainer of Damned-Lies https://git.gnome.org/browse/damned-lies/ (hosted here: https://l10n.gnome.org/) but sadly this great app is designed for the GNOME project ;)

**Comment by mitsuhiko** [comment]
@stephane I would do what I do on sentry which works really well.

**Pull request merged**
