### PR TITLE
Handle a publisher with no "yield" statement.

### PR DESCRIPTION
**Pull request by ajdavis**
Handle a publisher with no "yield" statement.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I think that might accidentally swallow exceptions. Maybe we should just remand a yield there. When would a publisher not yield?

**Comment by ajdavis** [comment]
I hit this problem with a publisher like:

``` python
class SurgePublisher(Publisher):
    def publish(self, target_url, credentials=None, **extra):
        url = target_url.path
        subprocess.check_call(['surge', '-p', self.output_path, url])
```

In the case of the Surge publisher, the "surge" command line tool prints all the output the user needs. The Publisher doesn't need to yield any log messages. So I was surprised when I got a TypeError, and I thought other plugin authors would be surprised too.

Another option is to do `if hasattr(publisher, "__iter__")`.

**Comment by mitsuhiko** [comment]
In this case the publisher should iterate over the output and yield it out. Maybe we can add a helper for this.  The reason is that otherwise the admin UI can't see the output of the publisher in the publish panel. The printing to stdout will only work for publishers that actually are invoked from the command line.  Not sure how applicable that is for the surge publisher because I assume it cannot be invoked from the admin panel if it starts prompting for user information.

**Comment by ajdavis** [comment]
I see - it should be invokable from the admin UI, actually. If it's configured right it requires no input. I've updated it to use Lektor's Command:

https://github.com/ajdavis/lektor-surge/commit/5bfe373dc1ec0bc7289cd85d6d52d40f6cf93b1f

**Pull request closed without merging**
