### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by lyenliang**
Add Chinese translation for Lektor.

### CODE REVIEW

**Comment by lyenliang** [comment]
Hi, I just made a mistake. `Remove duplicate error prefix` should be in another pull request.

**Comment by mitsuhiko** [comment]
Merging anyways :)

**Comment by mitsuhiko** [comment]
Thanks a bunch!

**Comment by lyenliang** [comment]
:)

**Comment by tylerlong** [comment]
@mitsuhiko @lyenliang 

I have a concern here: There are Simplified Chinese and Traditional Chinese. I just checked this PR and it is Traditional Chinese. 

Maybe we should rename the file to `zh_TW.json`, and in the future some one will contribute a PR for Simplify Chinese as `zh_CN.json`.  I don't know the rule of thumb here, maybe we can keep the tranditional Chinese one as `zh.json` as long as there is no naming conflications?

What do you think?

**Comment by mitsuhiko** [comment]
@tylerlong i'm happy to pull something that renames it to something else.  Not sure yet if the system supports loading proper locales correctly.  Might need some testing.

**Pull request merged**
