### PR TITLE
Add S3 as deploy target

### PR DESCRIPTION
**Pull request by spenczar**
This works for me locally. 

One big quirk: this is just letting boto handle credentials, so it looks in ~/.aws/credentials and in the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for creds instead of using lektor's flow. I didn't want to muck with cli.py too much before getting a second opinion on whether it's important to unify credential input.

Also todo: writing docs. Again, I wanted to get a feel for whether this code is worthwhile before diving into those.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I'm absolutely with this sort of thing being in Lektor. S3 is a very popular target. I think there are a few things to consider:
- will this support custom error pages somehow? What is the best way to go about this
- is boto a good dependency to always pull in? I'm absolutely happy to depend on boto but we should probably check what it depends on and if that will not cause problems going forward.
- what about cloudfront?

**Comment by geekpete** [comment]
Maybe make the s3 publishing component a plugin so that you only need to include boto and its dependencies if/when the plugin is installed.

**Comment by spenczar** [comment]
Glad to hear it!

> will this support custom error pages somehow? What is the best way to go about this

To get this publisher to work, you need to have already created the S3 bucket you're deploying to - just like with the other publishers, we expect the remote end to be properly prepared. When you're setting up the S3 bucket as a static website, it asks you to tell it a filename to use as it's index.html, and optionally a filename to use for all errors.

Right now, savvy users could create a static error page, like 404.html or something, with the normal Lektor workflow and then configure their S3 bucket to point to it as the error page. I think this is _definitely_ the right first step, and _probably_ the right long-term plan unless you expect to support error pages as a first-class concern, in which case the publishers would need to know about them - which seems too complex.

> is boto a good dependency to always pull in?

Yeah, boto is pretty big, so it's worth talking about. At first I hoped I could make this a plugin to dodge the issue, but plugins are not mature enough to support something like adding a new publisher.

In my experience, boto is a well-run project and doesn't break it's API much (ever?) so I wouldn't be too worried about it. Its transitive dependencies seem fine to me, but I've never run a large open-source project, so I'd defer to your judgement.

> what about cloudfront?

To serve from Cloudfront, you point Cloudfront at your S3 bucket. You'd still publish the same way. Cloudfront configuration is beyond the scope of Lektor, I'd think - just like we wouldn't have Lektor manage DNS aliases for github pages or S3 buckets.

**Comment by spenczar** [comment]
Thinking about a plugin for this - I guess I could hook onto the `setup-env` event, which is emitted when plugins are loaded (which happens at the top of the deploy command), and then the plugin could add a publisher to `lektor.publisher.publishers`, which is a global dictionary. Mutating that global seems pretty icky, but it's an option.

**Comment by spenczar** [comment]
I've written a plugin and it works pretty smoothly: https://github.com/spenczar/lektor-s3 (or `lektor plugins add lektor-s3`).

I'm OK with either way to do this. @mitsuhiko, could you make the call on whether to make this a part of lektor proper?

**Comment by mitsuhiko** [comment]
@spenczar plugin sounds like a good idea.  I think it would be easy to make a copy of publishers on the env and then let plugins modify that instead. Safer. Mind sending a PR for this?

**Comment by mitsuhiko** [comment]
In general I would like to expose publishers to plugins but probably still put the docs into the main lektor docs just because it makes more sense to find it there.

**Comment by spenczar** [comment]
Great - I can do that PR, yep. I'll do a second PR for adding the S3 plugin to docs.

**Pull request closed without merging**
