### PR TITLE
admin: fix checkboxes widget

### LINKED ISSUE #812: Checkboxes are not working
Checkboxes cannot be checked with version 3.2.0. Checkboxes work on prior versions. I used Firefox browser version 80.0.1. They also do not work on Brave browser.

### PR DESCRIPTION
**Pull request by yagebu**
### Issue(s) Resolved

Fixes #812

### Description of Changes

This change from a function to an arrow function allows us to access the
containing class with `this` in the line below.

### CODE REVIEW

**Comment by xlotlu** [comment]
This should make it straight to a release, no?

**Comment by runfalk** [comment]
Yeah, let's make this 3.2.1.

**Comment by yagebu** [comment]
I've created a `3.2-maintenance` branch and backported this patch to it.

**Comment by runfalk** [comment]
Wouldn't it make sense to just base the maintenance branch on current master? I think it's fine to include the JS version bumps and everything else. Would be nice if the CI on the maintenance branch was green as well.

**Comment by yagebu** [comment]
Yeah, why not :+1: , will do.

**Pull request merged**
