### PR TITLE
clarify .lektorproject file not found error message

### PR DESCRIPTION
**Pull request by briancappello**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Technically the `.lektorproject` file is optional though. Wonder if we should just lie about it.

**Comment by briancappello** [comment]
Hmm. Rereading the project file documentation I see that now - looks like it's discouraged though. A quick glance through the cli module suggests that a bit of functionality (info, plugins, ...) would be broken without a project file set up, is that correct? I originally ran into this while trying to add a plugin from the wrong directory - perhaps certain commands that depend on there being a project file should error early if none is found, and leave this specific error message as-is?

**Comment by mitsuhiko** [comment]
@briancappello yeah, you cannot use automatic plugin installation without a project file.

**Comment by briancappello** [comment]
@mitsuhiko OK, I'll chalk this up to an PEBKAC error on my end! I'll defer to your judgement as far as whether to close or merge goes.

**Pull request closed without merging**
