### PR TITLE
Implement standard for JS linting

### PR DESCRIPTION
**Pull request by singingwolfboy**
We should have a linting system for the Javascript in this project, and [Standard](http://standardjs.com/) is a good choice. I'm open to other options, though.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
@coreygrunewald, could you review this please?

**Comment by coreygrunewald** [comment]
I'll take a closer look this weekend, but in general, I would recommend creating a git pre-push script that runs the JS tests and linting, and then a Make task that symlinks the file into `.git/hooks/pre-push`. That way if people are inclined to symlink the hook, they will be notified of a failure before even pushing to `origin`.

**Comment by singingwolfboy** [comment]
@coreygrunewald: still hoping you can review this, if possible. The failed GitHub checks are due to code coverage issues, and for this pull request, I think it's totally reasonable to merge in spite of that, since there's no change to the functionality.

**Comment by tariquesani** [comment]
@singingwolfboy Can you give a hint on how to solve those failing tests? I just asked someone to write a test for their PR only to realise that they are broken...

**Comment by singingwolfboy** [comment]
@tariquesani There are two different checks happening here: whether the automated tests pass, and how well they cover the codebase. The second check is the problem here -- it's triggered when a pull request changes a lot of code that is not covered by automated tests. The fix is to write new automated tests that cover the lines that have been changed.

I don't think the tests are broken, it's just that there is a lot of untested code. We should incrementally write new tests to cover the untested code, and theoretically I should do that in this pull request. But this pull request is already large enough as it is, and as I said, there are no changes to the functionality, so it should be a safe change. That's why I'm advocating to merge this even when Codecov is reporting a failure. Does that make sense?

**Comment by tariquesani** [comment]
Understood, I got confused by what I have notice in https://github.com/lektor/lektor/issues/352

**Comment by singingwolfboy** [comment]
I'd really like to get this merged so that other PRs can build on top of it. It it needs further fixes, we can get them in future PRs.

**Comment by coreygrunewald** [comment]
Got wrapped up with work, sorry to leave this one hanging. In general though, LGTM.

**Pull request merged**
