### PR TITLE
Bugfix/validation

### PR DESCRIPTION
**Pull request by niijv**
-Disable the save button when any field has validation failures.
-Simplify integer and float parsing with regex.

### CODE REVIEW

**Comment by chipperdoodles** [comment]
Would an empty field present a validation error?

**Comment by niijv** [comment]
@chipperdoodles empty fields are always valid, afaik there is no concept of "required" or "non-empty" fields yet, but would not be hard to enforce on UI level atleast

Do you ask out of curiosity or is there a validation where empty returns a failure?

**Comment by chipperdoodles** [comment]
@niijv mostly curiousity, I prefer empty fields to be valid at them moment so I was wondering if there was a case where they weren't! thank you for filling me in.

**Comment by singingwolfboy** [comment]
@niijv: Thanks! This seems really good to me, but I'd like @mitsuhiko to weigh in before merging it -- I'm still pretty new to React.

Also, how difficult would it be to add an automated test or two to cover your changes? It looks like there's a `lektor/admin/spec` directory with only three Jasmine tests implemented, but it would be great to have more test coverage! Maybe you could work with @go-bears and @arbonap on this, related to #244?

**Comment by niijv** [comment]
Sure, i'll see what I can do!
@go-bears or @arbonap, could you point me to some good introductory material on how to do the Jasmine tests?

**Comment by arbonap** [comment]
@niijv Introduction to Jasmine testing: [Jasmine docs](http://jasmine.github.io/2.0/introduction.html)

**Comment by niijv** [comment]
Thanks @arbonap!

**Comment by singingwolfboy** [comment]
Hey @niijv, did you ever make any progress on those automated tests? It would be great to get this merged, but I'd like to have some test coverage before we do so.

**Comment by tariquesani** [comment]
Seems like a dead PR - can we close it?

**Comment by niijv** [comment]
Well, I rarely have time to come back to my open pull requests, but everytime I found some spare time in the last few months, the admin ui did not build correctly on windows. There have been some pull requests for this lately, but I am still unable to build the admin ui. Since nobody could reproduce it on Gitter, I think it must have to do something with my setup.

Once I sort this out I'll just reopen this pull request, you can close it for now.

**Pull request closed without merging**
