### PR TITLE
Added documentname and description properties to exif

### PR DESCRIPTION
**Pull request by tariquesani**
Added documentname and description properties to exif, this is useful to create self contained galleries.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Can you add automated tests for these properties?

**Comment by tariquesani** [comment]
Added the tests and an updated test image

**Comment by singingwolfboy** [comment]
Seems reasonable to me. Thanks!

**Comment by tariquesani** [comment]
Yay! Thanks.

**Pull request merged**
