### PR TITLE
Add datetime type

### PR DESCRIPTION
**Pull request by item4**
This PR implemented datetime type with timezone.
# Usage
## settings

``` ini
[fields.pub_date]
label = Publication date
type = datetime
```
## printing

``` html+jinja
{{ this.pub_date | datetimeformat('YYYY-MM-dd HH:mm:ss') }}
```
## Python default

```
pub_date: 2016-01-13 01:02:03
```
## With timezone abbreviations

```
pub_date: 2016-01-13 01:02:03 EST
```
## With timezone name

```
pub_date: 2016-01-13 01:02:03 America/Dominica
```
## With timedelta

```
pub_date: 2016-01-13 01:02:03 +0900
```

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Instead of importing `pytz` it would be cool if this would use the pytz indirection from babel.

**Comment by mitsuhiko** [comment]
In particular this thing: http://babel.pocoo.org/en/latest/api/dates.html#timezone-functionality

**Comment by item4** [comment]
Yes, I'll change it

**Comment by item4** [comment]
I remained `pytz.FixedOffset` for this case. (not timezone name, given timedelta)

```
pub_date: 2016-01-13 01:02:03 +0900
```

**Comment by item4** [comment]
I didn't add new filter for datetime. Aleady you added it as `datetimeformat`

**Comment by mitsuhiko** [comment]
That looks good! I will try to merge this on the weekend. Can you also send a pull request for docs against the website repo?

**Comment by item4** [comment]
I'll try it.

**Comment by ajdavis** [comment]
Ooh, I'm excited about this one!

**Comment by niijv** [comment]
DateTime Picker is in the works too.

**Pull request merged**
