### PR TITLE
Fix lektor server with LEKTOR_DEV when frontend source missing

### PR DESCRIPTION
**Pull request by dairiki**
If the `LEKTOR_DEV` environment variable is set, `lektor server` (among other things) tries to auto-rebuild the frontend js/css when it runs.  Currently, `lektor server` dies with a `FileNotFound` exception if LEKTOR_DEV set and the frontend source is not available.
The frontend source is only available when running Lektor from git source.  Specifically, it is not available when Lektor
has been installed from PyPI.

This PR fixes `lektor server` so that skip the frontend building if it can not find the frontend source, or if `npm` is not installed.

Currently `LEKTOR_DEV` enables all sorts of features in `lektor server`.   Most of these features are generally useful to devs working on templates, plugins, etc. in a Lektor project.

## Questions

Since the frontend rebuilding is only useful for devs actually working on the frontend — devs working on the Lektor source itself — perhaps a new trigger should be introduced to control this functionality?

### Issue(s) Resolved

Fixes #

### Related Issues / Links

lektor/lektor-website#353 also is concerned with the number and variety of features enabled by `LEKTOR_DEV`.

### Description of Changes

- [x] Wrote at least one-line docstrings (for any new functions)
- [x] Added unit test(s) covering the changes (if testable)
- [x] Link to corresponding documentation pull request for [getlektor.com](https://github.com/lektor/lektor-website)
       (This PR doesn't really change semantics of LEKTOR_DEV, so I'm going to say a doc PR, while nice-to-have is not required. Note there is already lektor/lektor-website#353 requesting more docs on LEKTOR_DEV.  )

### CODE REVIEW

**Comment by dairiki** [comment]
@yagegu Lying in bed last night, it occurred to me the the correct fix here is to delete this functionality altogether.

Those of us who work on the frontend code — that probably two people: you and me ­— are probably the only ones who benefit from this automatic running of `npm run dev` by `lektor server`.  I can certainly live if I have to start `npm run dev` manually in a separate window.

Can I just remove it?

**Comment by dairiki** [comment]
@yagebu  Lying in bed last night, it occurred to me the the correct fix here is to delete this functionality altogether.

Those of us who work on the frontend code — that probably two people: you and me ­— are probably the only ones who benefit from this automatic running of `npm run dev` by `lektor server`.  I can certainly live if I have to start `npm run dev` manually in a separate window.

Can I just remove it?

**Comment by nixjdm** [comment]
I say go for it. I never used it either - partly because I didn't realize it existed for the longest time, but regardless.

**Comment by dairiki** [comment]
I've added a commit that simply removes all the frontend rebuild logic.  If @yagebu approves that plan, this PR should be **squash-merged**.

**Review by yagebu — APPROVED** [review]
LGTM, I'm for removing it as well. I never really used it (for Lektor frontend dev) since running it in a separate window was just as easy (and a bit better to work with on errors and the like).

**Pull request merged**
