### PR TITLE
New option: _always_build.

### PR DESCRIPTION
**Pull request by ajdavis**
Ensure some artifacts are built even if nothing depends on them. For example, on my site, there is an Atom feed consumed by Planet Python but nothing on my site links to it. Or, if you have HTML redirect pages from old locations on your site, you want those built even though nothing refers to them on your own site.

### CODE REVIEW

**Comment by ajdavis** [comment]
If you like this idea I'll submit documentation too.

**Comment by mitsuhiko** [comment]
So generally +1 on the idea, I just also want to quickly throw this into the ring: #37

Maybe we can build it somehow that the same key can be used for this. The main idea was also that plugins can customize this.

**Comment by ajdavis** [comment]
I _think_ this is totally distinct from #37. In #37 we rebuild an artifact
even if Lektor thinks it's up to date. In this PR, we do the _first_ build
of an artifact, even if Lektor thinks it shouldn't be built at all. Once an
always_build artifact is built, Lektor decides whether to rebuild using the
usual logic.

I should come up with a different name than always_build. How about is_root?

They are related and should be configured in a way that's consistent for
the user, but I think the implementation of the two features is separate.

**Comment by mitsuhiko** [comment]
Ah I see. I wonder why this happens though. Should this not be found just by iterating over the children? I assume this might happen because a pagination filter now restricts what we iterate over?

**Comment by ajdavis** [comment]
Yes that's right. In my case, the page at https://emptysqua.re/blog/ has pagination enabled, so the build program iterates over child pages that match the pagination filter. That excludes some things like my Atom feeds, which wouldn't be built at all unless I find some way to force it. HTML redirect pages would have the same problem.

**Comment by mitsuhiko** [comment]
I think we should solve this somehow differently. Things not included by pagination should still be included for the builder automatically.

**Comment by ajdavis** [comment]
Ah I see. I should mark such sources "undiscoverable". I'll leave a more general solution to you, I didn't realize I could fix this with the existing Lektor code.

**Comment by mitsuhiko** [comment]
@ajdavis i think there should be a bug opened that if something is missed by the pagination that they are not picked up by the build process if that's the case.

**Comment by ajdavis** [comment]
OK, I've opened #132.

**Pull request closed without merging**
