### PR TITLE
Support Python 3

### LINKED ISSUE #142: Support Python 3
[@mitsuhiko want someone's PR](https://gitter.im/lektor/lektor?at=56aee398586242210ae0b531)
## Issue
- ~~Can we use [six](https://pythonhosted.org/six/) for keep same operation?~~
- Can we use [tox](https://tox.readthedocs.org/en/latest/) for testing?
- Can we use [coveralls](https://coveralls.io/) for checking coverage?
- Can lektor's dependencies support py3?

### PR DESCRIPTION
**Pull request by singingwolfboy**
Fixes #142. Depends on #205 and #206 -- and I'm happy to pull some of these changes out into other, smaller pull requests if you prefer.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Neat! I will try to review it over the weekend.

**Comment by singingwolfboy** [comment]
@mitsuhiko: Fantastic! Now that you've merged the other PRs I made, I've rebased this branch onto the latest version of `master`, so there are fewer commits to look at.

As you can see from Travis, all the automated tests pass. In addition, I tried running `lektor quickstart` and `lektor server` on Python 3, and discovered a few more bugs which I also fixed, but that indicates lack of coverage in the test suite. I added two small new tests, but I wasn't sure how to test the larger stuff. Please pay special attention to the last few commits in this PRs, since those are the ones that fix bugs that do not have associated automated tests. (I'd be happy to write more automated tests, if I had someone to guide me through how to write the necessary tests.)

Once this is working properly on Python 3, I'm going to try building my own Lektor-powered site. If I do so successfully, then I volunteer to maintain Python 3 support for Lektor, since I'll be doing it anyways. :)

**Comment by singingwolfboy** [comment]
@mitsuhiko: Any update on this pull request?

**Comment by mitsuhiko** [comment]
Hi @singingwolfboy. Sorry i was so busy with other things. Any chance we could talk about this PR this week on gitter/irc?

**Comment by singingwolfboy** [comment]
@mitsuhiko has given me commit rights on the project, so that I can support Lektor on Python 3. Let me know if I've missed anything! Thanks, @mitsuhiko!

**Comment by sybrenstuvel** [comment]
When will we see a release that includes this? The last release is over a year old.

**Comment by tariquesani** [comment]
Wish there could be a fixed date. The development is stalled at the moment.

**Comment by austinbutler** [comment]
So with this merged and Lektor 3.1 released, does that mean Python 3 is supported?

**Comment by nixjdm** [comment]
@austinbutler Yes.

**Pull request merged**
