### PR TITLE
Feature/collapsing flow elements

### PR DESCRIPTION
**Pull request by jtraub91**
I implemented a simple collapse by adding another button to action-bar and adding a props.value[idx].collapsed flag. Also, I made a small modification to the main.less file so that action bar remains right justified when collapsed.

### CODE REVIEW

**Comment by nixjdm** [comment]
Thanks @jtraub91! It looks like this is failing the linter. Could you take a look and fix those issues? To run it locally, in `lektor/admin` run `npm run lint`. Or from the Make file, right at the top level dir, `make test-js`.

**Comment by goanpeca** [comment]
@jtraub91 this is great work! now to be able to quickly inspect PRs that affect the UI, could you make a small animation?

Perhaps using something light weight like https://www.cockos.com/licecap/ ?


---

@nixjdm we use this template for PRs, might be useful to have something similar

https://github.com/spyder-ide/spyder/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Also 

https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by jtraub91** [comment]
Thanks @nixjdm and @goanpeca ! Here's an animation of the feature:
lektor_flow_collapse

I'm happy to include the pull request template. But I'm a bit confused: Is this something I attach here in the comments? Or commit it to the master branch of my fork? How would it get attached to this PR? 

Also, do the one-line docstring and unit test requirements apply here?

**Comment by goanpeca** [comment]
@jtraub91 do not worry about the template comment. @nixjdm or I can handle that! Thanks for the screencast :-)

**Pull request merged**
